import re
from utils.llm_client import get_llm_response

class DeveloperAgent:
    """
    Generates patched code based on the RCA using Search/Replace blocks.
    """
    def generate_fix(self, rca: str, original_code: str) -> str:
        prompt = f"""
        Based on the Root Cause Analysis, fix the original code.

        # Root Cause Analysis (RCA)
        {rca}
        
        # Original Code
        ```python
        {original_code}
        ```
        
        Instead of returning the entire file, you must output SEARCH/REPLACE blocks to patch the code.
        The SEARCH section must exactly match the existing lines of code.
        
        Format:
        <<<<
        [exact lines from original code]
        ====
        [new lines to insert]
        >>>>
        
        You can output multiple blocks if needed. 
        """
        system_instruction = "You are an expert Developer Agent. Output your changes strictly as SEARCH/REPLACE blocks. Do not wrap the blocks in markdown code blocks."
        
        response = get_llm_response(prompt, system_instruction=system_instruction)
        print("\n--- RAW LLM OUTPUT ---")
        print(response)
        print("----------------------\n")
        return self._apply_blocks(original_code, response)
        
    def _apply_blocks(self, original_code: str, llm_output: str) -> str:
        """Helper to extract and apply SEARCH/REPLACE blocks."""
        # Strip <think> tags often generated by OSS reasoning models
        llm_output = re.sub(r"<think>.*?</think>", "", llm_output, flags=re.DOTALL)
        
        patched_code = original_code
        # Find all <<<< ... ==== ... >>>> blocks
        blocks = re.findall(r"<<<<\n(.*?)\n====\n(.*?)\n>>>>", llm_output, re.DOTALL)
        
        if not blocks:
            # Fallback if the LLM ignored instructions and returned the whole file
            match = re.search(r"```[a-zA-Z]*\n(.*?)```", llm_output, re.DOTALL)
            if match:
                return match.group(1).strip()
            return original_code

        for search_text, replace_text in blocks:
            if search_text in patched_code:
                patched_code = patched_code.replace(search_text, replace_text)
            else:
                print(f"⚠️ Warning: Could not find block to replace:\n{search_text}")
                
        return patched_code
