from utils.sandbox import Sandbox

class ValidatorAgent:
    """
    Validates patched code by running tests in an isolated sandbox.
    """
    def validate(self, source_dir: str, target_file: str, patched_code: str) -> tuple[bool, str]:
        sandbox = Sandbox(source_dir)
        sandbox.setup()
        
        # Apply the fix generated by Developer Agent
        sandbox.apply_patch(target_file, patched_code)
        
        # Run tests (defaulting to pytest)
        passed, output = sandbox.run_tests(["pytest"])
        
        # Clean up isolated environment
        sandbox.cleanup()
        
        return passed, output
